Repository DOROEDU/Doro-Front, pull requests merged in 2023-07, with the labels that each got.

#32 [ 노세인 ] fcm 안드로이드 설정 추가, ios 마이페이지 수정
  App.js
  android/app/src/main/AndroidManifest.xml
  components/signUp/FindId.js
  components/signUp/FinishPw.js
  package-lock.json
  package.json
  screens/DeleteUser.js
  screens/HomeScreen.js
  screens/ProfileEdit.js
  screens/SearchPW.js
  utill/config.js
Labels: :bug: 버그, :iphone: UI, :gift: 기능, ⚙️ 설정

#34 [ 김민혁 ] - 로직 작동 시 리렌더링 추가, 신청한 강의 버튼 제어, 안드로이드 로고 추가
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
  package-lock.json
  package.json
  screens/DetailLectureScreen.js
  screens/HomeScreen.js
  screens/UpdateLectureScreen.js
Labels: :bug: 버그, :iphone: UI, :gift: 기능

#36 [김민혁] - 강의 상세 스크롤 문제 해결, 라이브러리 전체적 업데이트, 생년월일 선택사항 변경
  App.js
  babel.config.js
  components/feat/Timer.js
  components/signUp/AgreeInfo.js
  components/signUp/AgreeInfo2.js
  components/signUp/AuthPhone.js
  components/signUp/ChangePw.js
  components/signUp/Code.js
  components/signUp/FindId.js
  components/signUp/Finish.js
  components/signUp/FinishPw.js
  components/signUp/Id.js
  components/signUp/Name.js
  components/signUp/NotFindId.js
  components/signUp/Pw.js
  components/signUp/School.js
  components/ui/ButtonBig.js
  components/ui/ButtonOneThird.js
  components/ui/ButtonSmall.js
  components/ui/GenerationModal.js
  components/ui/Input.js
  components/ui/InputText.js
  components/ui/LectureTop.js
  components/ui/PwBtn.js
  components/ui/TutorBox.js
  constants/fonts.js
  package-lock.json
  package.json
  screens/AlarmScreen.js
  screens/ApplicationDetails.js
  screens/DeleteUser.js
  screens/DetailLectureScreen.js
  screens/EditNoticeScreen.js
  screens/LoginScreen.js
  screens/ManagerScreen.js
  screens/MyPageScreen.js
  screens/NoticeDetailScreen.js
  screens/NoticeScreen.js
  screens/ProfileEdit.js
  screens/SearchID.js
  screens/SearchPW.js
  screens/TutorScreen.js
  screens/UpdateLectureScreen.js
  store/LecturesProvider.js
  utill/config.js
Labels: :bug: 버그, :iphone: UI, :gift: 기능

#39 [ 노세인 ] 베타테스트 오류 해결
  components/signUp/Code.js
  components/ui/ApplyingLectureBox.js
  components/ui/LectureBox.js
  components/ui/TutorBox.js
  screens/ApplicationDetails.js
  screens/DetailLectureScreen.js
  screens/HistoryScreen.js
  screens/HomeScreen.js
  screens/UpdateLectureScreen.js
Labels: :bug: 버그, :iphone: UI

#41 [ 노세인 ] 생년월일 편집 추가, 생년월일 입력 한국어버전 변경
  components/signUp/Name.js
  components/signUp/School.js
  screens/ProfileEdit.js
  utill/config.js
  utill/http.js
Labels: :bug: 버그, :iphone: UI, :gift: 기능
